// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026web3.Data;

#nullable disable

namespace _2026web3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904121139_personPassportCreation")]
    partial class personPassportCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2026web3.Models.Pasaporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("personaId")
                        .IsUnique();

                    b.ToTable("Pasaporte");
                });

            modelBuilder.Entity("_2026web3.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("dob")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("_2026web3.Models.Pasaporte", b =>
                {
                    b.HasOne("_2026web3.Models.Persona", "Persona")
                        .WithOne("Pasaporte")
                        .HasForeignKey("_2026web3.Models.Pasaporte", "personaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("_2026web3.Models.Persona", b =>
                {
                    b.Navigation("Pasaporte");
                });
#pragma warning restore 612, 618
        }
    }
}
