// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026web3.Data;

#nullable disable

namespace _2026web3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908133731_CompletarCrudPersonas")]
    partial class CompletarCrudPersonas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MateriaPersona", b =>
                {
                    b.Property<int>("MateriasId")
                        .HasColumnType("int");

                    b.Property<int>("PersonasId")
                        .HasColumnType("int");

                    b.HasKey("MateriasId", "PersonasId");

                    b.HasIndex("PersonasId");

                    b.ToTable("Inscripcion", (string)null);
                });

            modelBuilder.Entity("_2026web3.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Materia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creditos = 4,
                            Name = "Programación Web"
                        },
                        new
                        {
                            Id = 2,
                            Creditos = 4,
                            Name = "Base de Datos"
                        },
                        new
                        {
                            Id = 3,
                            Creditos = 3,
                            Name = "Ingeniería de Software"
                        },
                        new
                        {
                            Id = 4,
                            Creditos = 3,
                            Name = "Redes"
                        });
                });

            modelBuilder.Entity("_2026web3.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Pais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brasil"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Perú"
                        });
                });

            modelBuilder.Entity("_2026web3.Models.Pasaporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("personaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("personaId")
                        .IsUnique();

                    b.ToTable("Pasaporte");
                });

            modelBuilder.Entity("_2026web3.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("dob")
                        .HasColumnType("date");

                    b.Property<int>("paisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("paisId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("MateriaPersona", b =>
                {
                    b.HasOne("_2026web3.Models.Materia", null)
                        .WithMany()
                        .HasForeignKey("MateriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2026web3.Models.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2026web3.Models.Pasaporte", b =>
                {
                    b.HasOne("_2026web3.Models.Persona", "Persona")
                        .WithOne("Pasaporte")
                        .HasForeignKey("_2026web3.Models.Pasaporte", "personaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("_2026web3.Models.Persona", b =>
                {
                    b.HasOne("_2026web3.Models.Pais", "Pais")
                        .WithMany("Personas")
                        .HasForeignKey("paisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("_2026web3.Models.Pais", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("_2026web3.Models.Persona", b =>
                {
                    b.Navigation("Pasaporte");
                });
#pragma warning restore 612, 618
        }
    }
}
